class AutocorrelationError(Exception):
    """An Exception for the tools.autocorrelation methods."""

    pass


class CassiopeiaError(Exception):
    """An general exception for the Cassiopeia software."""

    pass


class CassiopeiaTreeError(Exception):
    """An Exception class for the CassiopeiaTree class."""

    pass


class DataSimulatorError(Exception):
    """Generic error for the DataSimulator subclasses"""

    pass


class DistanceSolverError(Exception):
    """An Exception class for all DistanceSolver subclasses."""

    pass


class ecDNABirthDeathSimulatorError(Exception):
    """An ExceptionClass for ecDNABirthDeathSimulator class."""

    pass


class FitchCountError(Exception):
    """An ExceptionClass for FitchCount."""

    pass


class GreedySolverError(Exception):
    """
    Error raised by greedy solver implementations.

    Returns
    -------
    GreedySolverError - Specialized exception for greedy solvers.
    """

    pass


class HybridSolverError(Exception):
    """An Exception class for all HybridSolver subclasses."""

    pass


class ILPSolverError(Exception):
    """An Exception class for all ILPError subclasses."""

    pass


class iTOLError(Exception):
    """
    Error raised by iTOL-related functionality.

    Returns
    -------
    iTOLError - Specialized exception for iTOL operations.
    """

    pass


class LeafSubsamplerError(Exception):
    """An Exception class for the LeafSubsampler class."""

    pass


class PreprocessError(Exception):
    """
    Error raised during preprocessing routines.

    Returns
    -------
    PreprocessError - Specialized exception for preprocessing utilities.
    """

    pass


class PriorTransformationError(Exception):
    """An Exception class for generating weights from priors."""

    pass


class SharedMutationJoiningSolverError(Exception):
    """An Exception class for SharedMutationJoiningSolver."""

    pass


class TreeSimulatorError(Exception):
    """An Exception class for all exceptions generated by

    TreeSimulator or a subclass of TreeSimulator
    """

    pass


class UnknownCigarStringError(Exception):
    """
    Error raised when encountering an unsupported CIGAR string.

    Returns
    -------
    UnknownCigarStringError - Specialized exception for invalid CIGAR strings.
    """

    pass


class UnspecifiedConfigParameterError(Exception):
    """
    Error raised when required configuration parameters are missing.

    Returns
    -------
    UnspecifiedConfigParameterError - Specialized exception for configuration issues.
    """

    pass


class BranchLengthEstimatorError(Exception):
    """An Exception class for the BranchLengthEstimator class."""

    pass


class IIDExponentialMLEError(BranchLengthEstimatorError):
    """
    Error raised during IID exponential maximum likelihood estimation.

    Returns
    -------
    IIDExponentialMLEError - Specialized exception for IID exponential MLE failures.
    """

    pass


class TreeMetricError(Exception):
    """An Exception class for calculating tree metrics"""

    pass


class ParameterEstimateError(Exception):
    """An Exception class for the estimation and retrieval of tree parameters"""

    pass


class PlottingError(Exception):
    """
    Error raised by plotting utilities.

    Returns
    -------
    PlottingError - Specialized exception for plotting operations.
    """

    pass
