class CassiopeiaTreeWarning(UserWarning):
    """A Warning for the CassiopeiaTree class."""

    pass


class DataSimulatorWarning(UserWarning):
    """Warning raised by data simulator utilities.

    Returns:
        DataSimulatorWarning - Specialized warning for simulator feedback.
    """

    pass


class PreprocessWarning(UserWarning):
    """Warning emitted during preprocessing workflows.

    Returns:
        PreprocessWarning - Specialized warning for preprocessing alerts.
    """

    pass


class SharedMutationJoiningSolverWarning(UserWarning):
    """A warning class for SharedMutationJoiningSolver."""

    pass


class ParameterEstimateWarning(UserWarning):
    """An warning class for the estimation and retrieval of tree parameters."""

    pass


class PlottingWarning(UserWarning):
    """Warning generated by plotting utilities.

    Returns:
        PlottingWarning - Specialized warning for visualization issues.
    """

    pass


class LeafSubsamplerWarning(UserWarning):
    """Warning specific to leaf subsampling helpers.

    Returns:
        LeafSubsamplerWarning - Specialized warning for subsampling notices.
    """

    pass
