version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
    - system_packages: true
submodules:
  include:
     - "docs/user_guide/notebooks"
  recursive: true
