version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
python:
  version: 3.6
  install:
    - method: setuptools
      path: .
      extra_requirements: 
      - docs
    - requirements: docs/requirements.txt
