"""Functional lineage tracing data simulators for Cassiopeia."""

import math
import warnings
from collections.abc import Callable
from colorsys import hsv_to_rgb

import networkx as nx
import numpy as np
import pandas as pd
import treedata as td

from cassiopeia.mixins import DataSimulatorError
from cassiopeia.utils import _get_parameter, _normalize_missing


def stochastic_tracing(
    tdata: td.TreeData,
    number_of_cassettes: int = 10,
    size_of_cassette: int = 3,
    mutation_rate: float | list[float] = 0.1,
    state_generating_distribution: Callable[[], float] = lambda: np.random.exponential(1e-5),
    number_of_states: int = 100,
    state_priors: dict | list[dict] | None = None,
    initiation_rate: float | None = None,
    continuation_rate: float | None = None,
    unmodified_state: str = "*",
    random_seed: int | None = None,
    tree_key: str = "simulated",
    time_key: str = "time",
    key_added: str = "characters",
    copy: bool = False,
) -> td.TreeData:
    """Simulate stochastic lineage tracing data on a tree.

    Simulates the accumulation of heritable mutations at genomic target sites
    as cells divide. Target sites are organised into cassettes — groups of
    independently-editable positions that share a silencing fate during dropout.
    Each site starts in ``unmodified_state`` and transitions irreversibly to a
    mutant state drawn from ``state_priors`` when edited. Results are stored
    as strings on every node and summarised in a leaf-level DataFrame.

    Editing can follow two kinetic models selected by ``initiation_rate``:

    * **Independent** (default): each open site is cut independently at
      ``mutation_rate`` per unit time (exponential process).
    * **Sequential** (``initiation_rate`` provided): a cassette first initiates
      at its leftmost site after an exponential wait, then continues editing
      subsequent sites left-to-right, each separated by an independent
      exponential wait at ``continuation_rate``.

    Results are written in-place to ``tdata``:

    * ``tdata.obsm[key_added]``: ``pd.DataFrame`` (n_leaves × n_chars),
      columns named ``"C-I"`` (cassette, site).
    * ``tree.nodes[node][key_added]``: character state dict for every
      node (leaves and internal).
    * ``tdata.uns["cassette_size"]``, ``tdata.uns["unmodified_state"]``:
      stored for :func:`missing_data`.

    Missing data (heritable dropout, stochastic silencing, resections) is
    handled separately — call :func:`missing_data` after this function.

    Examples:
        GESTALT (McKenna et al., Science 2016)::

            stochastic_tracing(tdata, number_of_cassettes=3, size_of_cassette=10)

        Chan et al. Cas9 indels (Chan et al., Nature 2019)::

            stochastic_tracing(tdata, number_of_cassettes=10, size_of_cassette=3)

        DNA Typewriter (Choi et al., Nature 2022)::

            stochastic_tracing(
                tdata,
                number_of_cassettes=10,
                size_of_cassette=5,
                initiation_rate=0.01,
                continuation_rate=0.2,
                state_priors={str(i): 1 / 16 for i in range(1, 17)},
            )

        PEtracer (Koblan et al., Science 2025)::

            stochastic_tracing(
                tdata,
                number_of_cassettes=10,
                size_of_cassette=3,
                state_priors={str(i): 1 / 8 for i in range(1, 9)},
            )

    Args:
        tdata: TreeData with a tree in ``obst[tree_key]``.
        number_of_cassettes: Number of cassette arrays.
        size_of_cassette: Number of editable sites per cassette.
        mutation_rate: Cutting rate (exponential parameter) for the independent
            model. Float or list of length ``size_of_cassette`` (tiled across
            cassettes) or ``number_of_cassettes * size_of_cassette``. Ignored
            in sequential mode.
        state_generating_distribution: Distribution for sampling state
            likelihoods when ``state_priors=None``.
        number_of_states: Number of possible states generated by
            ``state_generating_distribution`` when ``state_priors=None``.
        state_priors: Prior probabilities for each mutant state. Single dict
            (shared across all sites), list of ``size_of_cassette`` dicts
            (tiled across cassettes), or list of ``n_chars`` dicts (one per
            site). If ``None``, priors are sampled from
            ``state_generating_distribution``.
        initiation_rate: Exponential rate for cassette initiation. Providing
            this activates **sequential mode**.
        continuation_rate: Exponential rate for sequential site editing after
            initiation. Required when ``initiation_rate`` is given.
        unmodified_state: String written to unedited sites. Default ``"*"``.
            Stored in ``tdata.uns["unmodified_state"]`` for downstream use.
        random_seed: NumPy random seed for reproducibility.
        tree_key: Key in ``tdata.obst`` for the tree.
        time_key: Node attribute key for branch lengths (default ``"time"``). Must be present on all nodes.
        key_added: Key used for ``obsm`` and node attributes.
        copy: If ``True``, operate on a copy of ``tdata`` and return the copy.
            If ``False`` (default), modify ``tdata`` in-place.

    Returns:
        Modified ``tdata``. If ``copy=True``, a new TreeData; otherwise the
        input modified in-place.

    Raises:
        DataSimulatorError: On invalid parameters.
    """
    if not isinstance(number_of_cassettes, int) or number_of_cassettes <= 0:
        raise DataSimulatorError("Specify a positive integer number of cassettes.")
    if not isinstance(size_of_cassette, int) or size_of_cassette <= 0:
        raise DataSimulatorError("Specify a positive integer number of cut-sites per cassette.")

    sequential = initiation_rate is not None
    n_chars = number_of_cassettes * size_of_cassette
    columns = [f"{c}-{i}" for c in range(number_of_cassettes) for i in range(size_of_cassette)]

    if sequential:
        if not isinstance(initiation_rate, (int, float)) or initiation_rate <= 0:
            raise DataSimulatorError("Initiation rate must be a positive float.")
        if continuation_rate is None:
            raise DataSimulatorError("continuation_rate is required in sequential mode.")
        if not isinstance(continuation_rate, (int, float)) or continuation_rate <= 0:
            raise DataSimulatorError("Continuation rate must be a positive float.")
    else:
        rate_per_char = _resolve_mutation_rate(mutation_rate, number_of_cassettes, size_of_cassette)

    priors_per_char = _resolve_state_priors(
        state_priors,
        state_generating_distribution,
        number_of_states,
        n_chars,
        size_of_cassette,
    )

    if copy:
        tdata = tdata.copy()

    if random_seed is not None:
        np.random.seed(random_seed)

    tree = tdata.obst[tree_key]
    char_arrays: dict[str, list[str]] = {node: [unmodified_state] * n_chars for node in tree.nodes}

    for node in nx.topological_sort(tree):
        if tree.in_degree(node) == 0:
            continue  # root stays all-unmodified

        parent = next(iter(tree.predecessors(node)))
        branch_len = tree.nodes[node][time_key] - tree.nodes[parent][time_key]
        array = char_arrays[parent].copy()

        if not sequential:
            open_sites = [i for i, s in enumerate(array) if s == unmodified_state]
            new_cuts = [
                site
                for site in open_sites
                if np.random.uniform() < 1 - np.exp(-branch_len * rate_per_char[site])
            ]
            array = _introduce_states(array, new_cuts, priors_per_char)
        else:
            for c in range(0, n_chars, size_of_cassette):
                if array[c] != unmodified_state:
                    # Already initiated — continue from next unedited site
                    time = 0.0
                    i = c + 1
                    while time < branch_len and i < c + size_of_cassette:
                        if array[i] == unmodified_state:
                            time += np.random.exponential(1 / continuation_rate)
                            if time < branch_len:
                                _edit_site(array, i, priors_per_char[i])
                        i += 1
                else:
                    # Uninitiated — wait for initiation then continue
                    i = c
                    time = np.random.exponential(1 / initiation_rate)
                    if time < branch_len:
                        _edit_site(array, i, priors_per_char[i])
                    i += 1
                    while time < branch_len and i < c + size_of_cassette:
                        if array[i] == unmodified_state:
                            time += np.random.exponential(1 / continuation_rate)
                            if time < branch_len:
                                _edit_site(array, i, priors_per_char[i])
                        i += 1

        char_arrays[node] = array

    chars = {node: dict(zip(columns, char_arrays[node], strict=False)) for node in tree.nodes}
    for node in tree.nodes:
        tree.nodes[node][key_added] = chars[node]

    obs_names = list(tdata.obs_names)
    all_states = list(dict.fromkeys(state for priors in priors_per_char for state in priors)) + [
        unmodified_state
    ]
    categorical_dtype = pd.CategoricalDtype(categories=all_states, ordered=True)

    tdata.obsm[key_added] = _build_characters_dataframe(
        chars, columns, obs_names, categorical_dtype
    )

    tdata.uns["cassette_size"] = size_of_cassette
    tdata.uns["unmodified_state"] = unmodified_state
    tdata.uns["missing_state"] = "-"
    tdata.uns["priors"] = priors_per_char
    tdata.uns[f"{key_added}_colors"] = _get_state_colors(
        all_states, custom={unmodified_state: "lightgray"}
    )

    if copy:
        return tdata


def missing_data(
    tdata: td.TreeData,
    heritable_rate: float = 0.0,
    stochastic_rate: float = 0.0,
    collapse_sites_on_cassette: bool = False,
    missing_state: str = "-",
    unmodified_state: str | None = None,
    key_added: str | None = None,
    random_seed: int | None = None,
    tree_key: str = "simulated",
    time_key: str = "time",
    characters_key: str = "characters",
    copy: bool = False,
) -> td.TreeData:
    """Apply heritable and stochastic missing data to a traced tree.

    Intended to be composed after :func:`stochastic_tracing`. Applies three
    types of missing data at the cassette level:

    **Heritable silencing** (``heritable_rate``): cassette-level
    transcriptional silencing modelled as an exponential process per branch.
    Silencing propagates from parent to all descendants — once a cassette is
    silenced at a node, all descendant nodes also have it silenced. Both
    internal nodes and leaves are affected.

    **Stochastic dropout** (``stochastic_rate``): assay-level cassette
    dropout applied only to leaf nodes with a fixed per-cassette probability.

    **Resection** (``collapse_sites_on_cassette=True``): when two or more sites
    in the same cassette were cut on a single branch (detected by comparing a
    node to its parent), all sites between the leftmost and rightmost cut are
    set to ``missing_state``. Resections propagate to all descendants of the
    node where they occurred.

    All three types write ``missing_state`` to all affected sites. The
    ``tdata.uns["cassette_size"]`` value written by :func:`stochastic_tracing`
    is used to determine cassette membership.

    Results are written in-place (or to ``key_added`` if specified):

    * ``tree.nodes[node][output_key]``: updated character dicts for all nodes
    * ``tdata.obsm[output_key]``: rebuilt from updated leaf attributes
    * ``tdata.uns["missing_state"]`` / ``tdata.uns["unmodified_state"]``

    Args:
        tdata: TreeData previously processed by :func:`stochastic_tracing`.
        heritable_rate: Per-branch exponential rate of cassette
            transcriptional silencing (heritable, propagates to descendants).
        stochastic_rate: Per-cassette dropout probability applied
            independently to each leaf (stochastic, assay sensitivity).
        collapse_sites_on_cassette: If ``True``, detect multi-cut cassettes by
            comparing each node to its parent and mark intermediate sites as
            ``missing_state``. Resections propagate to descendants.
        missing_state: String written to all sites in a silenced or resected
            cassette. Default ``"-"``.
        unmodified_state: String representing the wildtype / unedited state.
            If ``None``, uses ``tdata.uns["unmodified_state"]``; falls back to
            ``"*"``. Used for resection detection when
            ``collapse_sites_on_cassette=True``.
        key_added: If ``None`` (default), overwrites ``tdata.obsm[characters_key]``
            and node attributes at ``characters_key`` in-place. If a string,
            writes results to ``tdata.obsm[key_added]`` and node attributes at
            ``key_added``, leaving the originals untouched.
        random_seed: NumPy random seed for reproducibility.
        tree_key: Key in ``tdata.obst`` for the tree.
        time_key: Node attribute key for branch lengths (default ``"time"``). Must be present on all nodes.
        characters_key: Key to read character data from.
        copy: If ``True``, operate on a copy of ``tdata`` and return the copy.
            If ``False`` (default), modify ``tdata`` in-place.

    Returns:
        Modified ``tdata``. If ``copy=True``, a new TreeData; otherwise the
        input modified in-place.
    """
    if unmodified_state is None:
        unmodified_state = tdata.uns.get("unmodified_state", "*")

    if (heritable_rate == 0) and (stochastic_rate == 0) and not collapse_sites_on_cassette:
        warnings.warn(
            "No missing data will be applied since all rates are zero and "
            "collapse_sites_on_cassette is False. Returning original tdata.",
            stacklevel=2,
        )

    if copy:
        tdata = tdata.copy()

    if random_seed is not None:
        np.random.seed(random_seed)

    tree = tdata.obst[tree_key]
    columns = list(tdata.obsm[characters_key].columns)
    cassette_size = tdata.uns["cassette_size"]
    n_cassettes = len(columns) // cassette_size
    output_key = key_added if key_added is not None else characters_key

    # Check if characters are available as node attributes
    some_node = next(iter(tree.nodes))
    has_node_chars = characters_key in tree.nodes[some_node]

    if collapse_sites_on_cassette and not has_node_chars:
        raise DataSimulatorError(
            f"collapse_sites_on_cassette requires '{characters_key}' stored as node "
            f"attributes, but none were found. Ensure stochastic_tracing was called "
            f"first, or set collapse_sites_on_cassette=False."
        )

    if has_node_chars:
        # Snapshot original characters (from stochastic_tracing) for collapse detection
        original_chars: dict[str, dict[str, str]] = {
            node: dict(tree.nodes[node][characters_key]) for node in tree.nodes
        }
        # Working copy — all modifications go here
        chars: dict[str, dict[str, str]] = {node: dict(d) for node, d in original_chars.items()}
    else:
        original_chars = {}
        obsm_df = tdata.obsm[characters_key]
        obs_names_set = set(tdata.obs_names)
        default_row = dict.fromkeys(columns, unmodified_state)
        chars = {}
        for node in tree.nodes:
            if node in obs_names_set:
                chars[node] = {col: str(obsm_df.loc[node, col]) for col in columns}
            else:
                chars[node] = dict(default_row)

    # --- Resection (collapse) ---
    # Detected per-branch by comparing original chars of each node to its parent.
    # Propagated cumulatively to all descendants via collapsed_sites tracking.
    if collapse_sites_on_cassette and cassette_size > 1:
        collapsed_sites: dict[str, set[int]] = {}
        for node in nx.topological_sort(tree):
            if tree.in_degree(node) == 0:
                collapsed_sites[node] = set()
                continue
            parent = next(iter(tree.predecessors(node)))
            new_collapsed: set[int] = set()
            for cassette_idx in range(n_cassettes):
                start = cassette_idx * cassette_size
                end = (cassette_idx + 1) * cassette_size
                # New cuts on this branch: unmodified in parent, edited in child,
                # and not already collapsed from an ancestor
                new_cuts = [
                    i
                    for i in range(start, end)
                    if (
                        i not in collapsed_sites[parent]
                        and original_chars[parent][columns[i]] == unmodified_state
                        and original_chars[node][columns[i]] != unmodified_state
                    )
                ]
                if len(new_cuts) > 1:
                    for i in range(new_cuts[0], new_cuts[-1] + 1):
                        new_collapsed.add(i)
            collapsed_sites[node] = collapsed_sites[parent] | new_collapsed
            for i in collapsed_sites[node]:
                chars[node][columns[i]] = missing_state

    # --- Heritable silencing ---
    silenced: dict[str, set[int]] = {}
    for node in nx.topological_sort(tree):
        if tree.in_degree(node) == 0:
            silenced[node] = set()
            continue
        parent = next(iter(tree.predecessors(node)))
        branch_len = tree.nodes[node][time_key] - tree.nodes[parent][time_key]
        p = 1 - np.exp(-branch_len * heritable_rate)
        new_silenced = {c for c in range(n_cassettes) if np.random.uniform() < p}
        silenced[node] = silenced[parent] | new_silenced
        for c in silenced[node]:
            for i in range(c * cassette_size, (c + 1) * cassette_size):
                chars[node][columns[i]] = missing_state

    # --- Stochastic dropout (leaves only) ---
    for node in tree.nodes:
        if tree.out_degree(node) != 0:
            continue
        for c in range(n_cassettes):
            if np.random.uniform() < stochastic_rate:
                for i in range(c * cassette_size, (c + 1) * cassette_size):
                    chars[node][columns[i]] = missing_state

    for node in tree.nodes:
        tree.nodes[node][output_key] = chars[node]

    obs_names = list(tdata.obs_names)

    # Preserve categorical dtype and extend categories to include missing_state
    source_col = tdata.obsm[characters_key].iloc[:, 0]
    if hasattr(source_col.dtype, "categories"):
        existing_categories = list(source_col.dtype.categories)
    else:
        existing_categories = list(
            dict.fromkeys(
                str(v) for col in columns for v in tdata.obsm[characters_key][col].unique()
            )
        )
    new_categories = (
        existing_categories
        if missing_state in existing_categories
        else existing_categories + [missing_state]
    )
    categorical_dtype = pd.CategoricalDtype(categories=new_categories, ordered=True)

    tdata.obsm[output_key] = _build_characters_dataframe(
        chars, columns, obs_names, categorical_dtype
    )

    # Propagate existing colors and add "white" for missing_state
    source_colors_key = f"{characters_key}_colors"
    if source_colors_key in tdata.uns:
        colors_map = dict(zip(existing_categories, tdata.uns[source_colors_key], strict=False))
        colors_map.setdefault(missing_state, "white")
        tdata.uns[f"{output_key}_colors"] = [colors_map.get(cat, "white") for cat in new_categories]

    tdata.uns["missing_state"] = missing_state
    tdata.uns["unmodified_state"] = unmodified_state

    if copy:
        return tdata


def noise(
    tdata: td.TreeData,
    error_rate: float = 0.0,
    priors: dict | None = None,
    missing_state: str | None = None,
    key_added: str | None = None,
    random_seed: int | None = None,
    tree_key: str = "simulated",
    characters_key: str = "characters",
    copy: bool = False,
) -> td.TreeData:
    """Apply sequencing-error state miscalls to the character matrix.

    Models assay-level read errors that cause an observed character state to be
    miscalled as a different state. Unlike :func:`missing_data` (which drops
    states to ``missing_state`` and can propagate heritably), ``noise`` acts only
    on the observed leaf states and is **not heritable**: each leaf is treated
    independently.

    For each leaf and site, with probability ``error_rate`` the called state is
    replaced by a different state drawn from that character's prior distribution
    (excluding the current state, with the remaining probabilities
    renormalized). Missing states are never altered and are never introduced.

    Priors are not specified, they are imputed from the empirical per-character state
    distribution of the matrix (excluding missing states). Priors are keyed by
    the positional index of each character column.

    Args:
        tdata: TreeData with a character matrix in ``tdata.obsm[characters_key]``.
        error_rate: Per-site probability that a called state is miscalled.
        priors: Optional ``{char_index: {state: prob}}`` mapping. If ``None``,
            falls back to ``tdata.uns["priors"]`` then to imputed priors.
        missing_state: Value(s) indicating missing data. If ``None``, uses
            ``tdata.uns["missing_state"]`` (falling back to the package default).
        key_added: If ``None`` (default), overwrites ``tdata.obsm[characters_key]``
            (and matching leaf node attributes) in place. If a string, writes
            results to ``tdata.obsm[key_added]`` instead, leaving the original
            untouched.
        random_seed: NumPy random seed for reproducibility.
        tree_key: Key in ``tdata.obst`` for the tree.
        characters_key: Key to read character data from.
        copy: If ``True``, operate on a copy of ``tdata`` and return the copy.
            If ``False`` (default), modify ``tdata`` in-place.

    Returns:
        Modified ``tdata``. If ``copy=True``, a new TreeData; otherwise the
        input modified in-place.
    """
    if error_rate == 0:
        warnings.warn(
            "No noise will be applied since error_rate is zero. Returning original tdata.",
            stacklevel=2,
        )

    if copy:
        tdata = tdata.copy()

    if random_seed is not None:
        np.random.seed(random_seed)

    missing_set = _normalize_missing(_get_parameter(tdata, "missing_state", missing_state))

    matrix = tdata.obsm[characters_key]
    columns = list(matrix.columns)
    output_key = key_added if key_added is not None else characters_key

    if priors is None:
        priors = _impute_priors(matrix, missing_set)

    # Apply miscalls column by column, preserving categorical dtype.
    result = {}
    for idx, col in enumerate(columns):
        source = matrix[col]
        values = source.astype(object).to_numpy().copy()
        char_priors = priors.get(idx) or {}
        states = list(char_priors.keys())
        weights = np.array([char_priors[s] for s in states], dtype=float)

        if error_rate > 0 and states:
            for i in range(len(values)):
                current = values[i]
                if current in missing_set:
                    continue
                if np.random.uniform() >= error_rate:
                    continue
                # Draw a replacement state, excluding the current one.
                keep = [s != current for s in states]
                alt_states = [s for s, k in zip(states, keep, strict=True) if k]
                if not alt_states:
                    continue
                alt_weights = weights[keep]
                total = alt_weights.sum()
                p = alt_weights / total if total > 0 else None
                values[i] = np.random.choice(alt_states, p=p)

        if hasattr(source.dtype, "categories"):
            categories = list(source.dtype.categories)
            for s in states:
                if s not in categories:
                    categories.append(s)
            result[col] = pd.Categorical(
                values, categories=categories, ordered=source.dtype.ordered
            )
        else:
            result[col] = values

    new_matrix = pd.DataFrame(result, index=matrix.index)
    tdata.obsm[output_key] = new_matrix

    # Keep leaf node attributes in sync if characters are stored on the tree.
    tree = tdata.obst[tree_key]
    some_node = next(iter(tree.nodes))
    if characters_key in tree.nodes[some_node]:
        for leaf in new_matrix.index:
            if leaf in tree.nodes:
                node_chars = dict(tree.nodes[leaf].get(characters_key, {}))
                for col in columns:
                    node_chars[col] = new_matrix.loc[leaf, col]
                tree.nodes[leaf][output_key] = node_chars

    if copy:
        return tdata


def _impute_priors(matrix: pd.DataFrame, missing_set: set) -> dict[int, dict[str, float]]:
    """Impute per-character priors from the empirical state distribution.

    For each column, computes the frequency of each non-missing state and uses
    it as that character's prior. Columns are keyed by positional index.
    """
    priors: dict[int, dict[str, float]] = {}
    for idx, col in enumerate(matrix.columns):
        observed = [v for v in matrix[col].astype(object) if v not in missing_set]
        counts = pd.Series(observed).value_counts()
        total = counts.sum()
        priors[idx] = {state: count / total for state, count in counts.items()} if total > 0 else {}
    return priors


def _build_characters_dataframe(
    chars: dict[str, dict[str, str]],
    columns: list[str],
    obs_names: list[str],
    categorical_dtype: pd.CategoricalDtype,
) -> pd.DataFrame:
    return pd.DataFrame(
        {
            col: pd.Categorical(
                [chars[n][col] for n in obs_names],
                dtype=categorical_dtype,
            )
            for col in columns
        },
        index=obs_names,
    )


def _resolve_mutation_rate(
    mutation_rate: float | list[float],
    n_cassettes: int,
    cassette_size: int,
) -> list[float]:
    n_chars = n_cassettes * cassette_size
    if isinstance(mutation_rate, np.ndarray):
        mutation_rate = mutation_rate.tolist()
    if isinstance(mutation_rate, (int, float)):
        if mutation_rate < 0:
            raise DataSimulatorError("Mutation rate needs to be non-negative.")
        return [float(mutation_rate)] * n_chars
    elif isinstance(mutation_rate, list):
        if np.any(np.array(mutation_rate) < 0):
            raise DataSimulatorError("Mutation rate needs to be non-negative.")
        if len(mutation_rate) == n_chars:
            return mutation_rate
        elif len(mutation_rate) == cassette_size:
            return mutation_rate * n_cassettes
        else:
            raise DataSimulatorError(
                "Length of mutation rate array is not the same as the number "
                "of characters or the number of cassettes."
            )
    else:
        raise DataSimulatorError("Mutation rate needs to be a float or a list.")


def _resolve_state_priors(
    state_priors: dict | list[dict] | None,
    state_generating_distribution: Callable[[], float],
    number_of_states: int,
    n_chars: int,
    cassette_size: int,
) -> list[dict]:
    if state_priors is None:
        probs = sorted(
            (state_generating_distribution() for _ in range(number_of_states)),
            reverse=True,
        )
        Z = np.sum(probs)
        prior = {str(i + 1): p / Z for i, p in enumerate(probs)}
        return [prior] * n_chars

    if isinstance(state_priors, np.ndarray):
        state_priors = state_priors.tolist()

    if isinstance(state_priors, dict):
        if not math.isclose(np.sum(list(state_priors.values())), 1.0):
            raise DataSimulatorError("Mutation priors do not sum to 1.")
        return [state_priors] * n_chars
    elif isinstance(state_priors, list):
        if not all(isinstance(item, dict) for item in state_priors):
            raise DataSimulatorError("State priors must be a dict or list of dicts.")
        n_cassettes = n_chars // cassette_size
        for prior in state_priors:
            if not math.isclose(np.sum(list(prior.values())), 1.0):
                raise DataSimulatorError("Mutation priors do not sum to 1.")
        if len(state_priors) == n_chars:
            return state_priors
        elif len(state_priors) == cassette_size:
            return state_priors * n_cassettes
        else:
            raise DataSimulatorError(
                "Length of mutation prior array is not the same as the number "
                "of characters or the number of cassettes."
            )
    else:
        raise DataSimulatorError("State priors must be a dict or list of dicts.")


def _introduce_states(
    array: list[str],
    cuts: list[int],
    priors_per_char: list[dict],
) -> list[str]:
    updated = array.copy()
    for i in cuts:
        states = list(priors_per_char[i].keys())
        probs = list(priors_per_char[i].values())
        updated[i] = np.random.choice(states, p=probs)
    return updated


def _edit_site(array: list[str], site: int, prior: dict) -> None:
    states = list(prior.keys())
    probs = list(prior.values())
    array[site] = np.random.choice(states, p=probs)


def _get_state_colors(categories: list, custom=None) -> list[str]:
    """Generate color palette for states."""
    n = len(categories)

    if n <= len(godsnot_102):
        colors = dict(zip(categories, godsnot_102[:n], strict=True))
    else:
        sampled_colors = [
            "#{:02x}{:02x}{:02x}".format(*(int(255 * c) for c in hsv_to_rgb(i / n, 0.85, 0.95)))
            for i in range(n)
        ]
        colors = dict(zip(categories, sampled_colors, strict=True))

    colors.update(custom or {})
    return [colors[cat] for cat in categories]


# from https://godsnotwheregodsnot.blogspot.com/2012/09/color-distribution-methodology.html
godsnot_102 = [
    "#FFFF00",
    "#1CE6FF",
    "#FF34FF",
    "#FF4A46",
    "#008941",
    "#006FA6",
    "#A30059",
    "#FFDBE5",
    "#7A4900",
    "#0000A6",
    "#63FFAC",
    "#B79762",
    "#004D43",
    "#8FB0FF",
    "#997D87",
    "#5A0007",
    "#809693",
    "#6A3A4C",
    "#1B4400",
    "#4FC601",
    "#3B5DFF",
    "#4A3B53",
    "#FF2F80",
    "#61615A",
    "#BA0900",
    "#6B7900",
    "#00C2A0",
    "#FFAA92",
    "#FF90C9",
    "#B903AA",
    "#D16100",
    "#DDEFFF",
    "#000035",
    "#7B4F4B",
    "#A1C299",
    "#300018",
    "#0AA6D8",
    "#013349",
    "#00846F",
    "#372101",
    "#FFB500",
    "#C2FFED",
    "#A079BF",
    "#CC0744",
    "#C0B9B2",
    "#C2FF99",
    "#001E09",
    "#00489C",
    "#6F0062",
    "#0CBD66",
    "#EEC3FF",
    "#456D75",
    "#B77B68",
    "#7A87A1",
    "#788D66",
    "#885578",
    "#FAD09F",
    "#FF8A9A",
    "#D157A0",
    "#BEC459",
    "#456648",
    "#0086ED",
    "#886F4C",
    "#34362D",
    "#B4A8BD",
    "#00A6AA",
    "#452C2C",
    "#636375",
    "#A3C8C9",
    "#FF913F",
    "#938A81",
    "#575329",
    "#00FECF",
    "#B05B6F",
    "#8CD0FF",
    "#3B9700",
    "#04F757",
    "#C8A1A1",
    "#1E6E00",
    "#7900D7",
    "#A77500",
    "#6367A9",
    "#A05837",
    "#6B002C",
    "#772600",
    "#D790FF",
    "#9B9700",
    "#549E79",
    "#FFF69F",
    "#201625",
    "#72418F",
    "#BC23FF",
    "#99ADC0",
    "#3A2465",
    "#922329",
    "#5B4534",
    "#FDE8DC",
    "#404E55",
    "#0089A3",
    "#CB7E98",
    "#A4E804",
    "#324E72",
]
